#!/bin/bash

_fullscriptpath="$(readlink -f ${BASH_SOURCE[0]})"
export DOTFILEDIR="$(dirname $_fullscriptpath)"

# set to true if you use tmux
USE_TMUX="true"

. $DOTFILEDIR/tmux
. $DOTFILEDIR/env
. $DOTFILEDIR/aliases
. $DOTFILEDIR/kubernetes
. $DOTFILEDIR/utils
. $DOTFILEDIR/gopowerline

if [ -d $DOTFILEDIR/private ]; then
    for f in $DOTFILEDIR/private/*; do
        . $f
    done
fi
